In [76]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
sv=SVC()
lr=LogisticRegression()
rf=RandomForestClassifier()

In [77]:
from sklearn.datasets import load_digits
data=load_digits().data
target=load_digits().target

In [78]:
from sklearn.model_selection import StratifiedKFold

In [87]:
kf=StratifiedKFold(n_splits=3)
svm=[]
lrs=[]
rfs=[]

In [88]:
def get_score(model,x_train,y_train,x_test,y_test):
    model=model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [89]:
for train_index,test_index in kf.split(data,target):
    x_train,x_test,y_train,y_test=data[train_index],data[test_index],target[train_index],target[test_index]
    svm.append(get_score(sv,x_train,y_train,x_test,y_test))
    lrs.append(get_score(lr,x_train,y_train,x_test,y_test))
    rfs.append(get_score(rf,x_train,y_train,x_test,y_test))

C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [92]:
rfs

[0.9315525876460768, 0.9465776293823038, 0.9298831385642737]

In [93]:
lrs

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [94]:
svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [103]:
from sklearn.model_selection import cross_val_score
score_svm=cross_val_score(sv,x_train,y_train)
score_rf=cross_val_score(rf,x_train,y_train)
score_lr=cross_val_score(lr,x_train,y_train)

C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [109]:
score_lr,score_rf,score_svm

(array([0.87916667, 0.975     , 0.9125    , 0.93305439, 0.9790795 ]),
 array([0.89166667, 0.96666667, 0.87916667, 0.94142259, 0.958159  ]),
 array([0.92916667, 0.975     , 0.95      , 0.9539749 , 0.9874477 ]))

In [ ]:
from 